from typing import List

from pydantic import BaseModel, Field, ConfigDict
from langchain_core.documents import Document


class GraphState(BaseModel):
    """
    Shared state for the financial regulatory compliance graph.

    The state is passed between:
        Guardrail
        Query Rewriter
        Hybrid Retriever
        Retrieval Router
        Web Search Fallback
        Generator
        Compliance Auditor
    """

    # ========================================================
    # PYDANTIC CONFIGURATION
    # ========================================================

    # LangChain Document objects are not standard Pydantic
    # types, so arbitrary_types_allowed is required.
    model_config = ConfigDict(arbitrary_types_allowed=True)

    # ========================================================
    # USER INPUT
    # ========================================================

    question: str = Field(description=("The original raw question asked by the user."))

    # ========================================================
    # INPUT GUARDRAIL
    # ========================================================

    is_safe: bool = Field(
        default=False,
        description=(
            "Whether the input is considered safe and "
            "relevant to financial or regulatory compliance."
        ),
    )

    # ========================================================
    # QUERY REWRITING
    # ========================================================

    search_queries: List[str] = Field(
        default_factory=list,
        description=(
            "Optimized regulatory search queries generated " "by the query rewriter."
        ),
    )

    # ========================================================
    # RETRIEVED DOCUMENTS
    # ========================================================

    documents: List[Document] = Field(
        default_factory=list,
        description=(
            "Retrieved regulatory document chunks or " "web-search fallback documents."
        ),
    )

    # ========================================================
    # GENERATED ANSWER
    # ========================================================

    generation: str = Field(
        default="",
        description=("The current answer generated by the " "compliance assistant."),
    )

    # ========================================================
    # WEB SEARCH
    # ========================================================

    web_search_used: bool = Field(
        default=False,
        description=("Whether the Tavily web-search fallback " "was used."),
    )

    # ========================================================
    # COMPLIANCE AUDIT
    # ========================================================

    is_compliant: bool = Field(
        default=False,
        description=(
            "Whether the current generated answer passed "
            "the factual compliance audit."
        ),
    )

    audit_feedback: str = Field(
        default="",
        description=(
            "Feedback produced by the compliance auditor "
            "when the generated answer fails validation."
        ),
    )

    # ========================================================
    # AUDIT / REGENERATION LOOP
    # ========================================================

    loop_count: int = Field(
        default=0,
        description=("Number of generator-auditor regeneration " "attempts performed."),
    )
